# Generated by Django 4.2.6 on 2024-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
