# Generated by Django 4.2.6 on 2024-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=50),
        ),
    ]
