# Generated by Django 4.2.6 on 2024-03-26 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
    ]
